<?php

namespace Database\Seeders;

use App\Models\Admin\Staff;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CABOCHON EMERALD RING',
                'description' => '',
                'specifications' => 'Colombian Cabochon Emerald total Weight: 7.26Ct, 102 Round Brilliant Cut Diamonds Total Weight: 2,60Ct ',
                'materials' => 'Platinum and 18K Yellow Gold',
                'categories' => [Category::FINE_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Cabochon Emerald Ring.jpg', 'Cabochon Emerald Ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LA CONTESS RING (EP)',
                'description' => '',
                'specifications' => '88 Brilliant Cut Diamonds total weight: 4.00Ct  3 Brazilian Pearshaped Emeralds Total Weight: 0.30Ct.',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::FINE_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['La Contess Ring (EP).jpg', 'La Contess Ring (EP)2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LA CONTESS RING (WPD)',
                'description' => '',
                'specifications' => '88 Brizillian Diamond Cut Emeralds total weight: 3.52Ct, 3 Pearshaped Diamonds 0.60Ct ',
                'materials' => '18K Yellow Gold & Platinum',
                'categories' => [Category::FINE_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['La Contess Ring (WPD).jpg', 'Lacontess Ring (WPD) 2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LA CONTESSE RING (YPD)',
                'description' => '',
                'specifications' => '88 Brilliant Cut Diamonds total weight: 4.00Ct  3 Fancy Yellow Pearshaped Diamonds Total Weight: 0.90Ct',
                'materials' => '18K Yello Gold',
                'categories' => [Category::FINE_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Lacontess Ring (YPD).jpg', 'Lacontess Ring (YPD)2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'MILKY AQUA RING ',
                'description' => '',
                'specifications' => '1 Oval Cabochon Milky Aquamqrine 16mm X 12mm Total weight: 29.43Ct  160 Round Brilliant Cut Diamonds Total Weight:       ',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Milky Aqua Ring.jpg', 'Milky Aqua Ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PERIDOT FLOWER RONG',
                'description' => '',
                'specifications' => '1 Emerald Cut Peridot Total Weight: 42.00Ct, 302 Round Brilliant Diamonds total Weight: 1,21Ct',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::FINE_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Peridot Flower Ring.jpg', 'Peridot Flower ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PROFILE RING',
                'description' => '',
                'specifications' => '15 Round Brilliant Cut Diamonds Total weight: 0.65Ct, 2 Full Cut Diamonds Total Weight: 0.02Ct ',
                'materials' => '18K Yellow Gold & Platinum',
                'categories' => [Category::FINE_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Profile Ring.jpg', 'Profile Ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SLEEPING BEAUTY RING',
                'description' => '',
                'specifications' => '1 Rubelite Cabochon total Weight: 13.58Ct, 84 Round Brilliant Cut Diamonds Total Weight: 0.84Ct ',
                'materials' => '18K Yellow Gold & Platinum',
                'categories' => [Category::FINE_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Sleeping Beauty Ring.jpg', 'Sleeping Beauty Ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SOUTH SEA PEARL RING ',
                'description' => '',
                'specifications' => '1 South Sea Pearl measuring 13.5mm, 42 Brilliant Cut Diamonds Total Weight: 1.51Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['South sea Pearl Ring.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AGDAL EARRINGS (RUBY)',
                'description' => '',
                'specifications' => '2 Round Rubies Total Weight: 1.10Ct, 30 Round Diamonds total Weight: 0,54Ct, 248 Round Rubies Total Weight: 5.90Ct, 6 Straight Diamond Baguettes Total Weight: 0.29Ct',
                'materials' => '18K White Gold',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Agdal Earrings(Ruby).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AGDAL TWIRL EARRINGS (S&D)',
                'description' => '',
                'specifications' => '2 Round Sapphires Total Weight: 0.90Ct, 176 Round Briiliant Cut Diamonds Total Weight: 3.50Ct, 6 Straight Diamond Baguettes Total Weight: 0,29Ct, 108 Round SapphiresTotal Weight: 3.24Ct',
                'materials' => '18K White Gold',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Agdal twirl Earrings (S&D).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AQUA BRIOLETTE EARRINGS',
                'description' => '',
                'specifications' => '2 Aquamarine Briolettes Total Weight: 6.00Ct, 46 Round Brilliant Cut Diamonds Total Weight: 1.00Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Aqua Briolettes Drop Earrings.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'BUTTON PAVE EARIINGS',
                'description' => '',
                'specifications' => '600 Round Brilliant Cut Diamonds Total Weight: 6.00Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Button Pave Earrings.jpg', 'Button Pave Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CABOCHON EMERALDS EARRINGS',
                'description' => '',
                'specifications' => '2 Colombian Cabochon Emeralds Total Weight: 6.80Ct & 6.95Ct, 153 Round Brilliant Cut Diamonds Total Weight: 2.73Ct',
                'materials' => 'Platinum & 18K Yellow Gold',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Cabochon Emerald Earrings.jpg', 'Cabochon Emerald Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'DIAMONDS AND RUBY HOOPS',
                'description' => '',
                'specifications' => '14 Round Brilliant Cut Diammonds Total Weight: 0.88Ct, 24 Round Rubies Total Weight: 2.20Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Diamond and Ruby Hoops.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'DIAMOND BRIOLETTE EARRINGS ',
                'description' => '',
                'specifications' => '2 Round Diamonds Total Weight: 0.80Ct, Round Brilliant Cut Diamonds Total Weight: 2.40Ct, 14 Briolette Diamonds Total Weight: 6.26Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Diamonds Briolette Earrings.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'FANCY BROWN DIAMOND EARRINGS',
                'description' => '',
                'specifications' => '2 Fancy Brown Diamonds Total Weight: 2.70Ct, 2 Round Diamonds Total Weight: 0.70Ct, Round Brilliant Cut Diamonds Total Weight: 3.65Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Fancy Brown Daimond Earring.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LA CONTESSE EARRINGS (WPD)',
                'description' => '',
                'specifications' => '4 White pearshaped Diamonds Total Weihgt: 1.06Ct, 40 Roung Brazilian Emeralds Total Weight 1.55Ct',
                'materials' => 'Platinum & 18K Yellow Gold',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['La Contess Earrings (WPD).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LA CONTESSE EARRINGS (YPD)',
                'description' => '',
                'specifications' => '4 Yellow Pearshaped Diamonds Total Weight: 1.20Ct, 40 Round Brilliant Cut Diamonds Total Weight: 1.80Ct',
                'materials' => '18K Yellow  Gold Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['La Contess Earrings (YPD).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LA CONTESSE EARRINGS (EP)',
                'description' => '',
                'specifications' => '4 Brazilian Pearshaped Emeralds Total Weight: 1.20Ct, 40 Brilliant Cut Diamonds 1.80Ct',
                'materials' => '18K Yellow  Gold',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['La Contess Earrings(EP).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'MILKY AQUA EARRING',
                'description' => '',
                'specifications' => '4 Cabochon Oval Milky Aqua Total weight: 24.00Ct, 462 Round Brilliant Cut Diamonds total weight: 1.74Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['milky Aqua earrings.jpg', 'milky Aqua earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PASTEL BRIOLETTE EARRINGS',
                'description' => '',
                'specifications' => '2 Round Fancy Yellow DiamondsTotal Weight: 0.80Ct, Round Briiliant Cut Diamonds total Weight: 2.10Ct
                Round Fancy Vivid Yellow Diamonds Total Weight: 0.30Ct, 10 Briolette Pastel Color Sapphires Total Weight: 20.00Ct',
                'materials' => 'Platinum & 18K Yellow Gold',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Pastel Briolette Earrings.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PEAR & DROP DIAMOND EARRINGS',
                'description' => '',
                'specifications' => '2 Pearshaped Diamonds Total weight: 0.60Ct, 550 Round brilliant Cut Diamonds Total Weight: 5.65Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Pear and Drop Diamond Earrings.jpg', 'Pear and Drop Diamond Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PROFILE EARRINGS',
                'description' => '',
                'specifications' => '30 Round Brilliant Cut Diamonds Total Weight: 1.35Ct, 4 Full Cut Diamonds Total weight: 0.04Ct',
                'materials' => '18K Yellow Gold & Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Profile Earrings.jpg', 'Profile Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'RIAN DROP EARRINGS',
                'description' => '',
                'specifications' => '2 Center Round Diamonds , 12 Trillion shape Diamonds , 42 Round Brilliant Cut Diamonds Total weight: 3.60Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Raindrop Earrings.jpg', 'raindrop Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SHAR EARRINGS',
                'description' => '',
                'specifications' => '102 Brilliant Cut Diamonds Total Weight: 0.91Ct, 16 Square Cut Diamonds Total Weight: 1.17Ct, 12 Marque Diamonds Total Weight: 3.94Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Shar Earrings.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SLEEPING BEAUTY EARRINGS',
                'description' => '',
                'specifications' => '2 Cabochon Rubellite Total Weight: 18.70 Ct, 84 Round Brilliant Cut Diamonds Total Weight: 1.15Ct ',
                'materials' => '18K Yellow Gold & Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Sleeping Beauty Earrings.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SOLSTICE EARRINGS',
                'description' => '',
                'specifications' => '150 Round Brilliant Cut Diamonds Total Weight: 7.00Ct, 14 Briolette Diamonds Total Weight: 6.26Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Solstice Earrings.jpg', 'Solstice Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SOUTH SEA PEARL EARRINGS',
                'description' => '',
                'specifications' => '2 South Sea Pearl Measuring 12.3mm & 12.35mm, 174 Round Brilliant Cut Diamonds Total Weight: 6.22Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['South Sea Pearl Earrings.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'TUTTI FRUITI HOOPS',
                'description' => '',
                'specifications' => '276 Round Brilliant Cut diamonds Total Weight: 5.50Ct, 36 Fancy Intense Yellow Diamonds Total Weight: 0.82Ct, 36 Round Faceted Sapphires Total Weight: 1.15Ct, 
                36 Round Brilliant Cut Rubies Total Weight: 1.05Ct, 36 Round Brazilian Emeralds Total Weight: 0.70Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Tuti fruiti Hoops.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'WHITE HOOP DIAMOND EARRINGS',
                'description' => '',
                'specifications' => '420 Round Brilliant Cut Diamonds Total Weight: 8.45Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['White Diamond Hoops.png'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'EMERALD EYE CROCODILE',
                'description' => '',
                'specifications' => '21 Straight Baguette Diamonds Total weight: 5.85Ct, 252 Brilliant Cut Diamonds total Weight: 8.46Ct, 2 Cabochon Emeralds Total Weight: 0.05Ct',
                'materials' => '18K Yellow Gold ',
                'categories' => [Category::FINE_JEWELRY_BROOCHES_ID],
                'banner' => 'product-banner.png',
                'images' => ['Emerald Eye Crocodile.jpg', 'Emerald Eye Crocodile2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LADY LUCK PIN',
                'description' => '',
                'specifications' => '1 Oval Cabochon Burmese Ruby Total Weight: 3.25Ct, 1 Oval Cabochon Colombian Emerald Total Weight: 3.10Ct
                28 Fancy Intence Yellow Diamonds Total Weight: 0.52Ct, 26 Round Briliant Cut Diamonds Total Weight: 0.48Ct, 2 Round Burma Rubies Total Weight: 0.08Ct',
                'materials' => '18K Yellow Gold & Platinum',
                'categories' => [Category::FINE_JEWELRY_BROOCHES_ID],
                'banner' => 'product-banner.png',
                'images' => ['Lady Luck Pin.jpg', 'Lady LUCK Pin2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'RUBY EYE CROCODILE',
                'description' => '',
                'specifications' => '38 Straight Baguette Diamonds Total Weight: 4.25Ct, 6 Tappered Bagette Diamonds Total weight: 0.45Ct, 66 Brilliant Cut Diamonds Total Weight: 2.75Ct
                2 Cabochon Rubies Total Weight: 0.07Ct',
                'materials' => '18K Yellow Gold & Platinum',
                'categories' => [Category::FINE_JEWELRY_BROOCHES_ID],
                'banner' => 'product-banner.png',
                'images' => ['Ruby Eye Crocodile.jpg', 'Ruby Eye Crocodile2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ENAMEL EGG CHARM BRACELET',
                'description' => '',
                'specifications' => '26 Round Brilliant Cut Diamonds Total Weight: 0.28Ct with a Surprise angel',
                'materials' => '18K Yellow Gold and Red Enamel',
                'categories' => [Category::FINE_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['Enamel Egg Charm Bracelet.jpg', 'Enamel Egg Charm bracelet2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LA CONTESS BANGLE',
                'description' => '',
                'specifications' => '297 Round Brilliant Cut Diamonds Totol Weight: 14.90Ct, 12 Brazilian Pershaped Emeralds Total Wieght: 3.60Ct ',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::FINE_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['La Contess Bangle.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PENGUIN CHARM BRACELET',
                'description' => '',
                'specifications' => '98 Round Brilliant Cut Diamonds Total Weight: 1.86Ct, 3 Burmese Rubies Total Weight: 0.06Ct an Black Enamel',
                'materials' => '18K Yellow & White Gold',
                'categories' => [Category::FINE_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['Penguin Charm bracelet.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PROFILE BRACELET',
                'description' => '',
                'specifications' => '110 Round Brilliant Cut Diamonds Total Weight:  3.04Ct',
                'materials' => '18K Yello Gold & Platinum',
                'categories' => [Category::FINE_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['Profile Bangle.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LOVE STRUCK BRACELET(D&R)',
                'description' => '',
                'specifications' => '49 Round Faceted Rubies Total Weight: 0.98Ct, 49 Round Brilliant Cut Diamonds Total Weght: 0.73Ct ',
                'materials' => '18K White Gold',
                'categories' => [Category::FINE_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['Love Struck bracelet(D&R).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SOLSTICE BRACELET',
                'description' => '',
                'specifications' => '126 Round Brilliant Cut Diamonds Total Weight: 6.30Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['Solstice Bracelet.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LOVE STRUCK BRACELET(D)',
                'description' => '',
                'specifications' => '98 Brilliant Cut Diamonds Total Weight: 3.52Ct, ',
                'materials' => '18K Yellow Gold and Platinum',
                'categories' => [Category::FINE_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['Love struck Bracelet(D).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CAPPED PEARL NECKLACE',
                'description' => '',
                'specifications' => '65 Round Brilliant Cut Diamonds Total Weight: 1.00Ct, 14 High Quality Baroque white Pearls measuring 15.50mm – 11.5mm',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::FINE_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Cupped pearl Necklace.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LA CONTESS NECKLACE',
                'description' => '',
                'specifications' => '812 Brilliant Cut Diamonds Total Weight: 41Ct, 30 Brazilian Pear-shape Emeralds Total Weight: 9.00Ct ',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::FINE_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['La Contess Necklace.jpg', 'La Contess Necklace2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LOVE STRUCK NECKLACE',
                'description' => '',
                'specifications' => '210 Brilliant Cut Diamonds Total Weight: 5.00Ct',
                'materials' => '18K Yellow & White Gold',
                'categories' => [Category::FINE_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Love struck Necklace.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PROFILE NECKLACE',
                'description' => '',
                'specifications' => '182 Round Diamonds Total Weight: 7.88Ct, 28 Full Cut Diamonds Total Weight:0.28Ct',
                'materials' => '18K Yello Gold & Platinum',
                'categories' => [Category::FINE_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Profile Necklace.jpg', 'Profile Necklace2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'LOVE STRUCK NECKLACE (R&D)',
                'description' => '',
                'specifications' => '105 Round Rubies Total Weight: 2.10Ct, 105 Brilliant Cut Diamonds Total Weight: 1.65Ct',
                'materials' => '18K White Gold',
                'categories' => [Category::FINE_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Love Struck Necklace (R&D)).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SHAR NECKLACE',
                'description' => '',
                'specifications' => '57 Brilliant Cut Diamonds Total Weight: 1.12Ct, 10 Square Cut Diamonds:Total Weight: 1.52Ct, 6 Marque Diamonds Total Weight: 3.81',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Shar Necklace.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SOLSTICE NECKLACE',
                'description' => '',
                'specifications' => '130 Brilliant Cut Diamonds Total Weight: 5.50Ct, 6 Briolette Diamonds Total Weight: 9.96Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Solstice necklace.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'TULIP PEARL NECKLACE',
                'description' => '',
                'specifications' => '90 Brilliant Cut Diamonds Total Weight: 1.38Ct, 15 High Quality Broque White Pearls measuring 15.5mm – 11.5mm',
                'materials' => '18K Yellow Glod',
                'categories' => [Category::FINE_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Tulip Pearl Necklace.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AGDAL RUBY PENDANT',
                'description' => '',
                'specifications' => '1 Round Rubies Total Weight: 1.00Ct, 39 Round and Baguette Diamonds total Weight: 0,80Ct, 115 Round Rubies Total Weight: 5.50Ct',
                'materials' => '18K White Gold',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Agdal Ruby Pendant.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AGDAL TWIRL PENDANT (S&D)',
                'description' => '',
                'specifications' => '1 Round Sapphires Total Weight: 1.00Ct, 89 Round and Baguette Diamonds Total Weight: 3.15Ct, 72 Round SapphiresTotal Weight: 2.20Ct',
                'materials' => '18K White Gold',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Agdal Twirl Pendant (SD).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AMORE HEART SHAPE PENDANT (D)',
                'description' => '',
                'specifications' => '94 Brilliant Cut Diamonds Total Weight: 2.26Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Amore Heart Shape Pendant (D).jpg', 'Amore Heart Shape Pendant (D)2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AMORE HEART SHAPE PENDANT (E) ',
                'description' => '',
                'specifications' => '24 Rilliant Cut Diamonds Total Weight: 0.41Ct, 70 Brazilian Round Emeralds Total Weight: 1.65Ct',
                'materials' => '18K Yellow  Gold ',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Amore Heart shape Pendant (E).jpg', 'Amore Heart Shape Pendant (E)2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AMORE HEART SHAPE PENDANT ®',
                'description' => '',
                'specifications' => '24 Rilliant Cut Diamonds Total Weight: 0.43Ct, 70 Round Rubies Total Weight: 1.72Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Amore Heart shape Pendant (R).jpg', 'Amore Heart Shape Pendant (R)2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AMORE HEART SHAPE PENDANT (s)',
                'description' => '',
                'specifications' => '24 Rilliant Cut Diamonds Total Weight: 0.41Ct, 70 Round Sapphires Total Weight: 1.65Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Amore Heart Shape Pendant (S).jpg', 'Amore Heart Shape Pendant (S)2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AQUA BRIOLETTE DROP PENDANT',
                'description' => '',
                'specifications' => '26 Brilliant Cut Diamonds Total weight: 0,68Ct, 1 Aquamarine Briolette Drop Total Weight: 10.28Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Aqua Briolette Drop Pendant.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'GRAND CROSS PENDANT',
                'description' => '',
                'specifications' => '55 Brilliant Cut Diamonds Total Weight: 5.00Ct,  Measuring: 50mm X 27mm ',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Grand cross Pendant.jpg', 'Grand Cross Pendant2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PENGUIN PENDANT (WG)',
                'description' => '',
                'specifications' => '98 Brillaint Cut Diamonds Total Weight: 1.86Ct, 3 Round Sapphires Total Weight: 0.06Ct ,  measuring 25.5mm X 15.5mm',
                'materials' => '18K White Gold and Enamel',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['penguin WG.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PENGUIN PENDANT (YG)',
                'description' => '',
                'specifications' => '59 Brilliant Cut Diamonds Total weight: 1.02Ct, Measuring 22mm X 12mm ',
                'materials' => '18K Yellow  Gold & Enamel',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['penguin YG.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PETITE CROSS PENDANT',
                'description' => '',
                'specifications' => '17 Brilliant Cut Diamonds Total Weight: 1.52Ct, ',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['petit Cross Pendant.jpg', 'petit Cross Pendant2.png'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'PETITE CROSS PENDANT (YG)',
                'description' => '',
                'specifications' => '17 Brilliant Cut Diamonds Total Weight: 1.52Ct, ',
                'materials' => '18K Yellow  Gold',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Petit cross (yG).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'RAINDROP PENDANT',
                'description' => '',
                'specifications' => '6 Trillion Cut Diamonds , and 16 Brilliant Cut Diamonds Total Weight: 2.10Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Raindrop pendant.jpg', 'Raindrop pendant2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'TAPPERED BAGUETTES CROSS',
                'description' => '',
                'specifications' => '5 Tappered Baguette Diamonds, 5 Brilliant Cut Diamonds, and 1 Princess Cut Diamond Total Weight: 1.42Ct',
                'materials' => 'Platinum',
                'categories' => [Category::FINE_JEWELRY_PENDANTS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Tapered Buguette Diamonds Cross.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Bascket Pearl Ring',
                'description' => '',
                'specifications' => '1 SOUTH South Sea Pearl Measuring 16.10mm X 16.40mm, 6 Black Cultured Pearls measuring 3.8mm, 86 Full Cut Diamonds Total Weight: 2.29Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Bascket Pearl Ring.jpg', 'Bascket Pearl Ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CELESTIAL Ring',
                'description' => '',
                'specifications' => 'Cushion Cut Kashmir Sapphire Total Weight 8.42Ct, 35 Tapered Diamond  Baguettes Total Weight: 5.35Ct, 380 Full Cut Diamonds Total Weight: 4.18Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Celestial Ring.jpg', 'Celestial Ring2.jpg', 'Celestial Ring3.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CORONATION Ring',
                'description' => '',
                'specifications' => 'Center Stone: Funcy Light Yellow Marque Diamonds Total Weight: 3.89Ct, Accompanied with GIA Certificate, Tapered Baguet Diamonds Total Weight: 3.84Ct 
                30 Fancy Intence Yellow Full Cut Diamonds total weight: 0.30Ct, 35 Full Cut Diamonds Total Weight: 0.35Ct',
                'materials' => 'Platinum & 18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Coronation Ring.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CROWN OF MUSO Ring',
                'description' => '',
                'specifications' => 'Center Stone: Colombian Faceted Cabochon Emerald Total Weight: 8.30Ct, 2 Falf- Moon Diamonds Total Weight: 1.40Ct, 
                124 Full Cut Diamonds Total Weight 2.48Ct, And 48 Funcy Vivid Yellow Diamonds Total Weight: 0.40Ct ',
                'materials' => 'Platinum & 18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Crown Of Muso.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'DREAMCATCHER Ring (WD)',
                'description' => '',
                'specifications' => '56 Full Cut Diamonds, 30 Cushion Cut Diamonds, 7 Round Brilliant Cut Diamonds Toatl Diamonds Weiight: 4.84Ct.  ',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Dreamcatcher Ring (WD).jpg', 'Dreamcatcher Ring (WD)2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'DREAMCATCHER Ring (E&D)',
                'description' => '',
                'specifications' => '142 Round Brilliant Cut Diamonds Total weight: 0.84Ct ,  11 Rrazilian Brilliant Cut Emerald Total weight: 0.83Ct ',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Dreamcatcher Ring (E&D).jpg', 'Dreamcatcher Ring (E&D)2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'DREAMCATCHER Ring (MCD)',
                'description' => '',
                'specifications' => '227 Round Brilliant Cut Diamonds Total Weight: 0.29Ct, 64 Funcy Color Round Diamonds Total Weight: 0.86Ct, 7 Fancy Color Fancy Shape Diamonds Total Weight: 2.80Ct',
                'materials' => '18K Rose Gold',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Dreamcatcher ring (MCD).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'DREAMCATCHER Ring PINK GOLD',
                'description' => '',
                'specifications' => '182 Round Brilliant Cut Diamonds Total Weight: 2.03Ct',
                'materials' => '18K Rose Gold',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Dreamcatcher ring Pink Gold.jpg', 'Dreamcatcher Ring Pink Gold2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'EMPIRE DOME RING',
                'description' => '',
                'specifications' => 'Center Stone:  Classic Colombian Cushion Cut Emerald Total Weight: 11.03Ct, acocompanied with AGL and Gublin Certificates Insignificant Oil. 
                236 Fancy Intence Yellow Diamonds Total Weight 1.47Ct, 244 Brilliant Cut Diamonds Total Weight: 5.70Ct. ',
                'materials' => '18K Yellow Gold and Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Empire Dome Ring.JPEG'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'EVERGREEN RING/ BROOCH',
                'description' => '',
                'specifications' => 'Center Stone: Vintage Peridot Total Weight: 58Ct, 195 Full Cut Diamonds Total Weight: 0.86Ct. ',
                'materials' => '18K Rose Gold',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Evergreen Ring Brooch.jpg', 'Evergreen Ring Brooch2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'FELICITY RING',
                'description' => '',
                'specifications' => 'Center Stone: Double Sided Cabochon Burma SapphireTotal Weifgt: 8.30Ct, Accompanied with AGTA certificate. 114 Full Cut Diamonds Total Weight: 0.15Ct  ',
                'materials' => '22K Yellow Gold and Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Felicity Ring.jpg', 'Felicity Ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'FLOURISH RING',
                'description' => '',
                'specifications' => 'Center Stone: Fancy Intence Green Diamond Total Weight: 3.46Ct, 42 Brilliant Cut Diamonds Total Weight: 6.70Ct, Accompanied with GIA certificate',
                'materials' => 'Platinum and 18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Flourish ring.jpg', 'Flourish ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'INTERLUDE RING ',
                'description' => '',
                'specifications' => 'Center Stone: Colombian Cushion Cut Emerald Total Weight: 9.61Ct Accompanied with AGL and Gublin CertificatesInsignificant Oil, 
                74 Full Cut Diamonds Total Weight:1.12Ct, 58 Funcy Intence Yellow Diamonds Total Weight: 0.26Ct, 32 Diamond Cut Emeralds Total Weight: 0.29Ct ',
                'materials' => '22K Yellow Gold and Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Interlude  Ring.jpg', 'Interlude Ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'MONARCH RING',
                'description' => '',
                'specifications' => '7 Round Diamonds and 42 Round Brilliant Cut Diamonds Total weight: 7.75Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Monarch Ring.jpg', 'Monarch Ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'OASIS RING',
                'description' => '',
                'specifications' => 'CenterStone: Colombian Sugarloaf Emerald Total Weight: 5.05Ct, 32 Round Brilliant Cut Diamonds Total Weight: 0.23Ct ',
                'materials' => '22K Yellow Gold and Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Oasis Ring.jpg', 'Oasis Ring2.png'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'STAR OF CEYLON RING',
                'description' => '',
                'specifications' => 'Center Stone: Cushion Cut Ceylon Sapphire Total Weight: 5.34Ct, Round Brilliant Cut Diamonds Total Weight: 2.55Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Star Of Seylon Ring.jpg', 'Star of Seylon2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SUNBURST RING',
                'description' => '',
                'specifications' => 'Center Stone: Fancy Light Yellow Radiant Cut Diamond Total Weight: 4.54Ct, accompanied with GIA Certificate, 
                16 Fancy Vivid Yellow Full Cut Diamonds Total Weight: 1.20Ct, 48 Full Cut Diamonds Total Weights: 5.00Ct ',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Sunburst Ring.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'THREE STONE RING',
                'description' => '',
                'specifications' => '2 Fancy Light Yellow Radiant Cut Diamonds Total Weight: 4.68Ct, 1 Radiant Cut Diamond Total Weight: 2.09Ct, Acompanied with GIA certificate DVVS1',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Three Stone Ring.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'TRANSCENDENCE RING',
                'description' => '',
                'specifications' => 'Tahitian Pearl Measuring 15.34mm, 19 Custom Cut Peridotes Total Weight: 1.75Ct, 127 Round Brilliant Cut Diamonds Total Weight: 1.95Ct.',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Transcendaence Ring.jpg', 'Transcendence ring2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'IMPERIAL JASMINE RING',
                'description' => '',
                'specifications' => 'Center Stone:  Classic Colombian Cushion Cut Emerald Total Weight: 11.03Ct, acocompanied with AGL and Gublin Certificates Insignificant Oil. 
                262 Full Cut Diamonds Total Weight: 0.31Ct, ',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Imperial Jasmine Ring.jpg', 'Imperial Jasmine Ring2.jpg', 'Imperial Jasmine Ring3.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Aphrodite Earrings',
                'description' => '',
                'specifications' => '12  Colombian Emerald Briolettes & 4 Emerald Sugarloafs Total Weight: 44.24Ct accompanied with an AGL Certificat               
                278 Full cut diamonds, 8 Square Cut Diamonds, 8 Baguette Cut Diamonds, 8 Marque Cut Diamonds Total Weight: 6.80ct',
                'materials' => 'Platinum & 18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Aphrodite Earrings.jpg', 'Aphrodite Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Aurora Earrings',
                'description' => '',
                'specifications' => '6 Briolette Spphires Total Weight: 20.00Ct, 82 Round Brilliant Cut Diamonds Total weight: 4.95Ct',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Aurora Earrings.jpg', 'Aurora Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Bascket South Sea Pearl Earrings',
                'description' => '',
                'specifications' => '1 cultured South Sae Pearl 12mm ,1 Cultured Tahitian Black Pearl 12MM , 12 Cultured Pearls 6 White and 6 Black. 36 Full cut Diamons Weight: 1.67CT',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Bascket South Sea Pearl Earrings.jpg', 'Bascket South Sea Pearl Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Brilliant Harmony Hoop Earrings',
                'description' => '',
                'specifications' => '300 Brilliant Cut Diamonds Total Wieght 30.40CT ',
                'materials' => '18K white Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Brilliant Harmony Hoop Earrings.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Brilliance Hoop  Earrings',
                'description' => '',
                'specifications' => '24 Baguette Diamonds Total weight : 15.00Ct,  and 252 Round Diamonds total Weight: 1.60ct',
                'materials' => '',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Brilliant Harmony Hoop Earrings.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Cascade Earrings',
                'description' => '',
                'specifications' => '2 Colombian Cushion Shape Emeralds Total Weight: 8.12CT, 6 Briolette Diamonds Total Weight:7.28CT, 186 Round Diamonds Total Weight  1.80ct.
                192 Fancy Intence Yellow Diamonds total Weight: 1.90Ct, 42 Round Diamonds Total Weight : 11.42CT accompanied with Gublin Certificate.',
                'materials' => 'Platinum & 18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => [],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Colors In Harmony Earrings',
                'description' => '',
                'specifications' => '2 Heart Shape Zambian Emeralds Total weight: 6.42Ct, 4 Pear Shape Diamods Total Weight: 2.12Ct
                2 Fancy Yellow Diamonds Total Weight: 1.39Ct, 2 Pear Shape Rubellite Total Weight: 20.06Ct',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Colors In Harmony.jpg', 'Colors In Harmony2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Dreamcatcher Earrings (Diamonds)',
                'description' => '',
                'specifications' => '140 Brilliant Cushion Cut Diamonds Total Weight: 30.85Ct',
                'materials' => '18K white Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Dreamcatcher Diamonds.jpg', 'Dreamcatcher Diamonds2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Dreamcatcher Earrings (Multi Color Dia )',
                'description' => '',
                'specifications' => '438 Round Brilliant Cut Cut Diamonds Total Weihgt: 0.84Ct, 87 Fancy Color Round Diamonds Total Weight: 5.31Ct
                57 Assorted Fancy Color Fancy Shape Diamonds Total Weight : 19.95Ct ',
                'materials' => '18K Rose Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Dreamcatcher multi color Diamonds.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Dreacatcher Earrings Pink Gold Earrings',
                'description' => '',
                'specifications' => '165 Round Brilliant Cut Diamonds  Total Weight: 15.01Ct',
                'materials' => '18K Rose Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Dreamcatcher Pink Gold.jpg', 'Dreamcatcher Pink Gold2.jpg', 'Dreamcatcher PINK gold3.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Dreamcatcher Earrings with Emeralds',
                'description' => '',
                'specifications' => '800 Round Brilliant Cut Diamonds Total Weight: 2.75Ct, 68 Brazilian Brilliant Cut Emeralds Total Weight: 7.04Ct ',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Dreamcatcher with Emeralds.jpg', 'Dreamcatcher with Emeralds2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Eclips Tahitian Pearl Earrings',
                'description' => '',
                'specifications' => '6 Tahitian Pearls 14.90mm – 9.30mm, 6 Brilliant Cut Diamonds Total weight: 0.70ct, 230 Full Cut Diamonds Total Weight: 1.61ct ',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Eclips Earrings.jpg', 'Eclips Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Entchanted Emerald Drop Earrings',
                'description' => '',
                'specifications' => '2 Colombian Emerald Cabochon Drops Total Weight 35.15Ct Accompanied with AGL certificate  No Oil – 2 Heart Shape Funcy Light Yellow Daimonds Total Weight: 6.70Ct
                4 Pearshaped Diamonds  Total Weight: 1.65Ct , 2 Diamond Beads Total Weight: 1.84Ct, Fancy Intence Yellow & White Diamonds Total Weight 0.45Ct. All Diamonds are GIA certified.',
                'materials' => '18K Yellow Gold & Platinum',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Entchanted Earrings.jpg', 'Entchanted Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Entwine Lariat Earrings',
                'description' => '',
                'specifications' => '319 Brilliant Cut Diamonds Total Weight 3.53Ct, 319 Fancy Intence Yellow Diamonds Total Weihgt: 3.53Ct, 32 Tappered Baguette Diamonds Total Weihgt: 3.30Ct',
                'materials' => '18K Yellow Gold & Platinum',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Entwine Lariat Earrings.jpg', 'Entwine Lariat Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Lily Earrings',
                'description' => '',
                'specifications' => '2 Colombian Emeralds Total Weight 8.18Ct Accompanied with AGL Certificate, 150 Diamonds: Round, Pearshaped & straight Buguettes Total Weight: 5.00Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Lily Earrings.jpg', 'Lily Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Love Sparckle Earrings',
                'description' => '',
                'specifications' => '110 Round Brilliant Cut Diamonds Total Weight: 2.32Ct , 168 Multi-Color Briolette Sapphires Total Weight: 75.85Ct',
                'materials' => '18K Rose Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Love Sparckle Earrings.jpg', 'Love Sparckle Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Moonglow Earrings ',
                'description' => '',
                'specifications' => '1 South Sea Pearl 14.5mm, 1 Tahitian Pearl 14,5mm, 8 Princesse Cut Diamonds Total Weight 1.60Ct, 16 Trilliant Cut Diamonds Total Weight 1.92Ct, 
                183 Tapered Baguette Diamonds Total Weight 3.32Ct, 80 Princesse Cut Diamonds Total Weight: 3.20Ct. ',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Moonglow Earrings.jpg', 'Moonglow Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Opulence Earrings',
                'description' => '',
                'specifications' => '2 Round Colombian Emeralds Total Weight 8.67Ct, 2 Cushion Cut Colombian Emeralds Total Weght: 25.16Ct  All Accompanied with AGL and Gublin Certificates Insignificant Oil.
                224 Micro Pave Round Brilliant Cut Diamonds Total Weight: 2.24Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Opulence Earrings.jpg', 'Opulence Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Radiance Earrings',
                'description' => '',
                'specifications' => '2 Colombian Emerald Cut Emeralds Total Weight 6.08Ct Accompanied withAGL Certificate No Oil. 2 Fancy Intence Cushion Cut Diamonds Total Weight 1.00Ct, 
                162 Full Curt Diamonds Total Weight : 1.15Ct ',
                'materials' => 'Platinum & 18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Radiance Earrings.jpg', 'Radiance Earrings2.jpg', 'Radiance Earrings3.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Silhouette Earrings',
                'description' => '',
                'specifications' => '2 Pearshaped Colombian Emeralds Total Weight 19.95Ct Accompanied with AGL and Gublin Certificates Minor Oil. 2 Asher Cut Diamonds Total Weight: 10.39Ct GIA Certs GVVS
                2 Marque Cut Diamonds Total Weight: 1.00Ct, 282 Fancy Intense Yellow Diamonds Total Weight: 1.41Ct.
                4 Round Brilliant Cut Diamonds Total Weight 2,44Ct , 64 Round Brilliants Cut Diamonds Total Weight : 0.70Ct. ',
                'materials' => '18K Yellow Gpld and Platinum',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Silhouette Earrings.jpg', 'Silhouette Earrings2.jpg', 'Silhouette Earrings3.jpg', 'Silhouette Earrings4.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Sunburst Earrings ',
                'description' => '',
                'specifications' => '2 Fancy Yellow Radiant Cut Diamonds Total Weight 2.56Ct, Accompanied with GIA Certificate . 28 Fancy Vivid Yellow Diamonds Total Weight: 1.40Ct
                56 Full Cut Diamonds Total Weight: 6.50Ct ',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Sunburst Earrings.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Transcendance',
                'description' => '',
                'specifications' => '1 Round Tahitian Pearl 14.30mm/14.33mm, 1 Tahitian Drop Pearl 17.68mm/12.64mm , 2 Millennium Cut Peridots 8.50Ct, 512 Full Cut Diamonds Total Weight 9.90Ct',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Transcendance Earrings.jpg', 'Transcendance Earrings2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ECLIPS BRACELET',
                'description' => '',
                'specifications' => '11 Tahitian Pearls measuring 10.30mm, ,335 Full Cut Diamonds Total Weight: 4.85Ct',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['Eclips Tahitian Pearl Bracelet.jpg', 'Eclips Tahitian pearl bracelet2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ETOILE BANGLE 5 ROW (WD)',
                'description' => '',
                'specifications' => '110 Round Brilliant Cut Diamonds Total Weight: 13.90Ct',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['ETOILE BANGLE 5 RAW (WD).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'EMBRACE BRACELET',
                'description' => '',
                'specifications' => '1120 Brilliant Cut Diamonds Total Weight: 14.13Ct, 101 Fancy Intense Yellow Diamonds Total Weifgt: 1.13Ct,
                101 Fancy Intense Pink Diamonds Total Weight: 1.35Ct, 101 Faceted Ceylon Sapphires total Weight: 1.89Ct, 101 faceted Emeralds Total Weight: 1.33Ct',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['Emrace Bracelet.jpg', 'Embrace Bracelet2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'RUBY BEADS BREACELATE',
                'description' => '',
                'specifications' => '398 Round Brilliant Cut diamonds Total Weight: 1.72Ct, Round Burmese Unheated Ruby Beads Total Weight: 165Ct',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['Ruby Beads Bracelet.jpg', 'Ruby Beads Bracelet2.jpg', 'Ruby Beads Bracelet3.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'TUTTI FRUITI BANGLE',
                'description' => '',
                'specifications' => '80 Round Brilliant Cut Diamonds Total weight: 2.36Ct, 28 Fancy Intense Yellow Diamonds Total Weight: 0.65Ct
                28 Round Diamond Cut Brazilian Emeralds Total weight: 0.73Ct, 28 Round Ceylon Sapphires Total Weight: 0,95Ct, 28 Round burmese Rubies Total Weight: 1.03Ct',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_BRACELET_ID],
                'banner' => 'product-banner.png',
                'images' => ['Tuti Fruiti Bangle.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CLEOPATRA Necklace',
                'description' => '',
                'specifications' => 'Center Stone: Colombian Sugarloaf Cut Cabochon Emerald Total Weight: 24Ct Accompanied with AGL Certificate No Oil,  2 Colombian Sugarloaf Cut Cabochon Emerals Total Weight: 10.04Ct, Accompanied with AGL certificate Moderate oil, 2 Sperssartite Total Weight: 8Ct,
                631 Full Cut Diamonds  Total Weight: 6.65Ct',
                'materials' => '18K Yellow Gold and Platinum',
                'categories' => [Category::HIGH_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Cleopatra Necklace.jpg', 'Cleopatra Necklace2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CUFF Necklace',
                'description' => '',
                'specifications' => '1325 Round Brilliant Cut Diamonds Total Weight : 28.00Ct',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Cuff Necklace.jpg', 'Cuff Necklace2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ECLIPS Necklace',
                'description' => '',
                'specifications' => '21 Tahitian Pearls measuring 12.90mm – 10.30mm, 335 Full Cut Diamonds Total Weight: 16.11Ct',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Eclips Tahitian Pearl Necklace.jpg', 'Eclips Tahitian Pearl Necklace2.jpg', 'Eclips tahitian pearl necklace3.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ENTWINE LARIAT Necklace',
                'description' => '',
                'specifications' => '136 Round Brilliant Cut Diamonds Total Weight: 6.46Ct, Fancy Intence Yellow Diamonds Total Weight: 4.04Ct
                30 Tapered Baguette Diamonds Total Weight: 3.30Ct.',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::HIGH_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Entwine Lariat Necklace.jpg', 'Entwine Lariat Necklace2.jpg', 'Entwine Lariat Necklace3.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'AURORA Necklace',
                'description' => '',
                'specifications' => '622 Round Brilliant Cut Diamonds Total Weight: 21.46Ct , 26 Briolette Diamonds Total Weight: 31.95Ct
                9 Multi-Color Briolette Diamonds Total Weight: 36,20Ct',
                'materials' => 'Platinum',
                'categories' => [Category::HIGH_JEWELRY_NECKLACE_ID],
                'banner' => 'product-banner.png',
                'images' => ['Aurora.jpg', 'Aurora2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Kismet Brooch',
                'description' => '',
                'specifications' => 'Cushion Cut Peridot Total Weight: 38.59Ct, Round Brilliant Cut Diamonds Total Weight: 3.20Ct',
                'materials' => '18K Yellow Gold & Platinum',
                'categories' => [Category::HIGH_JEWELRY_BROOCHES_ID],
                'banner' => 'product-banner.png',
                'images' => ['Kismet Peridot Brooch.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => '3 DIAMOND (R&P) RING',
                'description' => '',
                'specifications' => 'Center Stone: Round Diamond weight: 0.70Ct, Side Stones: 2 Pearshaped Diamonds Weight:0.56Ct,   20 Brilliant cut Diamonds Weight: 0.12Ct, Total Diamond Weight: 1.38Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['3 diamond (R_P) Ring.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => '3 DIAMONDS RING (EMC)',
                'description' => '',
                'specifications' => 'please refer to Rafka”s website I do by Rafka engagement rings',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['3 Diamonds ring (EMC).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => '3 ROUND DIAMONDS RING (RD)',
                'description' => '',
                'specifications' => 'please refer to Rafka”s website I do by Rafka engagement rings',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['3 Round Diamond  Ring (RD).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => '3 Stones Ring (Y&W) Princess cut ',
                'description' => '',
                'specifications' => 'Please refer to High jewelery rings ( 3 Stones Ring)',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['3 stones  ring (Y_W) princess cut.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CORONATION',
                'description' => '',
                'specifications' => 'PLease refer to High jewelery rings (CORONATION)',
                'materials' => 'Platinum & 18K Yellow Gold',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Coronation.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CUSHION CUT DIAMOND RING',
                'description' => '',
                'specifications' => 'Center Stone: cushion Cut Diamond weight: 2.70Ct, 56 Brilliant Cut Diamonds weight: 0.42Ct, Total Diamond weight: 3.12Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['cushion cut engagement ring.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ENGAGEMENT RING (3RSD)',
                'description' => '',
                'specifications' => '60 Brilliant Cut Diamonds weight: 0.24Ct, Center Round Diamond weight: 1.85Ct, total weight: 2.09Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Engagement Ring (3RSD).png'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ENGAGEMENT RING 1',
                'description' => '',
                'specifications' => 'please refer to Rafka”s website I do by Rafka engagement rings',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Engagement ring 1.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ENGAGEMENT RING 2',
                'description' => '',
                'specifications' => 'please refer to Rafka”s website I do by Rafka engagement rings',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Engagement ring 2.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ENGAGEMENT RING 3',
                'description' => '',
                'specifications' => 'please refer to Rafka”s website I do by Rafka engagement rings',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Engagement ring 3.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ENGAGEMENT RING 4',
                'description' => '',
                'specifications' => 'please refer to Rafka”s website I do by Rafka engagement rings',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Engagement ring 4.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ENGAGEMENT RING 5',
                'description' => '',
                'specifications' => 'please refer to Rafka”s website I do by Rafka engagement rings',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Engagement ring 5.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'ENGAGEMENT RING VERA',
                'description' => '',
                'specifications' => '',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Engagemnt Ring VERA.JPG'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'MARQUISE SHAPE ENGAGEMENT RING',
                'description' => '',
                'specifications' => 'please refer to Rafka”s website I do by Rafka engagement rings',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Marquise shape Diamond Ring.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'MONARCH RING',
                'description' => '',
                'specifications' => 'please refer to High jewelery rings (MONARCH RING)',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Monarch Ring.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'FANCY BROWN ORANGE OVAL DIAMOND RING',
                'description' => '',
                'specifications' => 'Center Stone: Brownish Yellowish Orange Oval Diamond weight: 1.27Ct, 112 brilliant Cut Diamonds weight: 0.41Ct accompanied with GIA certificate',
                'materials' => 'Platinum & 22 K yellow Gold',
                'categories' => [Category::I_DO_BY_RAFKA_ENGAGEMENT_RINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Oval fancy Brown Diamond ring.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => '3 Color Eternity Bands',
                'description' => '',
                'specifications' => 'Please refer to Rafka website I do by Rafka Wedding Bands',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['3 color Eternity Band.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => '3 and 4 Row Diamond platinum bands',
                'description' => '',
                'specifications' => 'Please refer to Rafka website I do by Rafka Wedding Bands',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['4_3 Row Platinum Diamond Bands.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => '5 Diamonds Eternity Band',
                'description' => '',
                'specifications' => '5 Square cut Diamonds Total weight: 2,54Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['5 Diamonds Eternity Band.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Eternity Band',
                'description' => '',
                'specifications' => '14 Round Diamonds Total weihgt: 7.42Ct, 112 Brilliant cut Diamonds 0.75Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Eternity Band.png'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'His and Hers Black Enamel Bands',
                'description' => '',
                'specifications' => 'Hers: 8 Princess Cut Diamonds Total Weight: 1.70Ct, His 1 Emrald Cut Diamond Total Weight: 0.50Ct. 
                His and Hers Platinum and Enamel Designs no Diamonds',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['His and hers black Enamel.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'His and Hers Bands',
                'description' => '',
                'specifications' => 'Hers: 40 brilliant Cut Diamonds 0.80 Ct, His Arrow Tip Design Platinum only.',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['His and Hers.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Large 3 Row Eternity Band',
                'description' => '',
                'specifications' => '54 Brilliant Cut Diamonds Total Weight: 10.52Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['large 3 raw eternity Band.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Marquise Diamonds Yellow Gold',
                'description' => '',
                'specifications' => 'Please refer to Rafka website I do by Rafka Wedding Bands',
                'materials' => '18K Yellow Gold',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Marquise diamonds Yellow Gold.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Marquise Diamonds Platinum',
                'description' => '',
                'specifications' => 'Please refer to Rafka website I do by Rafka Wedding Bands',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Mrquise diamond Platinum.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Oval Diamonds band',
                'description' => '',
                'specifications' => '108 Brilliant Cut Diamonds Total Weight: 1.08Ct, 9 Oval Shape Diamonds Total Weight: ',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Oval Diamond Band.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Platinum Buguette Cut Diamond Band',
                'description' => '',
                'specifications' => 'Please refer to Rafka website I do by Rafka Wedding Bands',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Platinum Baguette cut Diamonds Band.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'Platinum Brilliant Cut Diamods Band',
                'description' => '',
                'specifications' => '204 Brilliant Cut Diamonds Weight: 0.82Ct, 24 Round Diamonds 2.31Ct, Total Diamonds: 3.13Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Platinum Brilliant Cut Diamonds Band.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => '4 Platinum Diamond Bands',
                'description' => '',
                'specifications' => 'Please refer to Rafka website I do by Rafka Wedding Bands',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_ETERNITY_BANDS_ID],
                'banner' => 'product-banner.png',
                'images' => ['4 Platinum Diamond Bands.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CLASSIC RIVIERA NECKLACE',
                'description' => '',
                'specifications' => '101 Brilliant Cut Diamonds, Color grading : E- E, Clarity Grading: VVS, Total Weight: 21.10Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_RIVIERA_NECKLACES_ID],
                'banner' => 'product-banner.png',
                'images' => ['Classic Tennis Necklace.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'DIAMOND LINK CHAIN',
                'description' => '',
                'specifications' => '750 Brilliant Cut Diamonds Total Weight : 7.80Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_RIVIERA_NECKLACES_ID],
                'banner' => 'product-banner.png',
                'images' => ['Diamond Link Chain.jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CLASSIC RIVIERA BRACELET (RD)',
                'description' => '',
                'specifications' => '29 Round Diamonds Total Weight: 22.00Ct , 169 Brilliant Cut Diamonds Total Weight: 1.20Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_RIVIERA_BRACELETS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Classic Riviera  Bracelet (RD).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'RIVIERA BRACELETE (RSD)',
                'description' => '',
                'specifications' => '19 Round Diamonds, 19 Square Cut Diamonds, 288 Brilliant Cut Diamonds Total Weight: 16.41Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_RIVIERA_BRACELETS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Riviera  Bracelet (RSD).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'CLASSIC STUD EARRINGS (WD)',
                'description' => '',
                'specifications' => '36 brilliant Cut Diamonds weight: 0.17 Ct, 2 round Diamonds Weight: 1.42Ct, Diamonds Total weight: 1,59Ct ',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_STUD_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['Classic Stud Earrings(WD).jpg'],
            ],
            [
                'staff_id' => Staff::ADMIN_ID,
                'title' => 'SIGNATURE DIAMOND STUD EARRINGS',
                'description' => '',
                'specifications' => '136 Brilliant cut Diamonds weihgt: 0.65Ct, 2 Round Diamonds weight: 1.40Ct Diamonds Total weight: 2.05Ct',
                'materials' => 'Platinum',
                'categories' => [Category::I_DO_BY_RAFKA_STUD_EARRINGS_ID],
                'banner' => 'product-banner.png',
                'images' => ['signature Diamond Stud Earrings.jpg'],
            ],
        ];

        foreach ($products as $item) {
            $product = Product::firstOrCreate(
                [
                    'title' => $item['title'],
                ],
                [
                    'staff_id' => $item['staff_id'],
                    'description' => $item['description'],
                    'specifications' => $item['specifications'],
                    'materials' => $item['materials'],
                    'is_published' => true,
                ]
            );

            if ($product->wasRecentlyCreated) {
                $product->categories()->sync($item['categories']);
                $folderPath = database_path('seeders/data/images/products/');

                $product->clearMediaCollection('banner');
                //add banner image
                $product
                    ->addMedia($folderPath.$item['banner'])
                    ->preservingOriginal()
                    ->toMediaCollection('banner');

                $product->clearMediaCollection(get_class($product));
                //add images to product
                foreach ($item['images'] as $key => $image) {
                    $product
                        ->addMedia($folderPath.$image)
                        ->preservingOriginal()
                        ->withCustomProperties(['primary' => $key == 0, 'position' => ++$key])
                        ->toMediaCollection(get_class($product));
                }
            }
        }
    }
}
